[extend]
useDefault = true

[[allowlists]]
description = "Ignore virtual environments and baseline file"
paths = [
    '''venv/''',
    '''\.venv/''',
    '''node_modules/''',
    '''.gitleaks-baseline.json'''
]

[[allowlists]]
description = "OpenCV GAPI constants are not secrets"
targetRules = ["generic-api-key"]
regexes = [
    '''cv\.gapi\.CV_'''
]