services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: traffic-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_shovel rabbitmq_shovel_management; 
      docker-entrypoint.sh rabbitmq-server"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 12

  stream-processor:
    build: ./stream-processor
    container_name: stream-processor
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - QUEUE_NAME=edge_frames
      - FRAME_INTERVAL_S=1.0
      - JPEG_QUALITY=95
      - LOG_LEVEL=INFO
      # - STREAMS_FILE=/app/streams.json
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      # - SAVE_FRAMES_ONLY=true
      # - OUTPUT_DIR=/app/frames
      - USE_LOCALHOST=true
      - DB_POLL_INTERVAL_S=60
      - AWS_MQ_URI=amqp://${AWS_MQ_USERNAME}:${AWS_MQ_PASSWORD}@16.171.53.75:5672
      - OPENCV_FFMPEG_CAPTURE_OPTIONS=rtsp_transport;tcp|stimeout;5000000
    # volumes:
    #   - ./stream-processor/streams.json:/app/streams.json:ro


  yolox-service:
    build: ./yolox-service/yolox-consumer
    container_name: yolox-service
    depends_on:
      rabbitmq:
        condition: service_healthy
      stream-processor:
        condition: service_started
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - QUEUE_NAME=edge_frames
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped

